#******************************* BombCrypto Bot *********************************#
#────────────────────────────────────────────────────────────────────────────────#
#─██████████████───██████████████─██████████████───██████████████─██████████████─#
#─██░░░░░░░░░░██───██░░░░░░░░░░██─██░░░░░░░░░░██───██░░░░░░░░░░██─██░░░░░░░░░░██─#
#─██░░██████░░██───██░░██████████─██░░██████░░██───██░░██████░░██─██████░░██████─#
#─██░░██──██░░██───██░░██─────────██░░██──██░░██───██░░██──██░░██─────██░░██─────#
#─██░░██████░░████─██░░██─────────██░░██████░░████─██░░██──██░░██─────██░░██─────#
#─██░░░░░░░░░░░░██─██░░██─────────██░░░░░░░░░░░░██─██░░██──██░░██─────██░░██─────#
#─██░░████████░░██─██░░██─────────██░░████████░░██─██░░██──██░░██─────██░░██─────#
#─██░░██────██░░██─██░░██─────────██░░██────██░░██─██░░██──██░░██─────██░░██─────#
#─██░░████████░░██─██░░██████████─██░░████████░░██─██░░██████░░██─────██░░██─────#
#─██░░░░░░░░░░░░██─██░░░░░░░░░░██─██░░░░░░░░░░░░██─██░░░░░░░░░░██─────██░░██─────#
#─████████████████─██████████████─████████████████─██████████████─────██████─────#
#────────────────────────────────────────────────────────────────────────────────#
#                                                                                #
#********           https://github.com/afkapp/bombcrypto-bcbot           ********#
#********       Join Us on Telegram: https://t.me/bombcryptobcbot        ********#
#                                                                                #
#********************************************************************************#
#********************* Please consider buying me a coffee :) ********************#
#********************************************************************************#
#******** BUSD/BCOIN (BEP20): 0x8c38512beca8b0b06bf4e85f67ee64a7dcdaa11a ********#
#********************************************************************************#  
#                                                                                #
#   ██████╗░████████╗░██████╗  ██╗░░██╗███████╗██████╗░░█████╗░██╗░░░░░██████╗░  #
#   ██╔══██╗╚══██╔══╝██╔════╝  ██║░░██║██╔════╝██╔══██╗██╔══██╗██║░░░░░██╔══██╗  #
#   ██████╦╝░░░██║░░░╚█████╗░  ███████║█████╗░░██████╔╝███████║██║░░░░░██║░░██║  #
#   ██╔══██╗░░░██║░░░░╚═══██╗  ██╔══██║██╔══╝░░██╔══██╗██╔══██║██║░░░░░██║░░██║  #
#   ██████╦╝░░░██║░░░██████╔╝  ██║░░██║███████╗██║░░██║██║░░██║███████╗██████╔╝  #
#   ╚═════╝░░░░╚═╝░░░╚═════╝░  ╚═╝░░╚═╝╚══════╝╚═╝░░╚═╝╚═╝░░╚═╝╚══════╝╚═════╝░  #
#                                                                                #
#         [en] Enable to receive notification or a call if BCBOT stops.          #
#   [pt_br] Habilitar para receber notificação ou uma ligação se o BCBOT parar.  #
#                                                                                #
#********************************************************************************#

  # [en] BTS HERALD DISABLE = false | BTS HERALD ENABLE = true
  # [pt_br] BTS HERALD DESABILITADO = false | BTS HERALD HABILITADO = true
  herald_active: false

  #[en] Get your key: https://herald.btscenter.net
  #[pt_br] Obtenha a chave: https://www.btscenter.com.br/bts-herald 
  key-herald: '00000000000000'

  label: 'BCBOT-1'

#********************************************************************************#
#                                                                                #
#                IMPORTANT: Rename this file for btsherald.yaml                  #
#           IMPORTANTE: Renomear este arquivo para btsherald.yaml                #
#                                                                                #   
#********************************************************************************#